In BSLeDiscoveryTests and BSLeDiscovery partially fix testFoundPeripherals by undoing changes in commit approx 357503e .
Test still fails, but now log for testFoundPeripherals shows device advertising and RSSI:
—
2013-11-09 00:19:16.898 BLELister[7116:60b] This block should run only one time. &once: 0xdd648, once: 668158664
2013-11-09 00:19:16.902 BLELister[7116:60b] [[BSLeDiscovery sharedInstance] <BSLeDiscovery: 0x14d42cb0>
2013-11-09 00:19:16.903 BLELister[7116:60b] [[BSLeDiscovery sharedInstance] centralManager] <CBCentralManager: 0x14e1ab10>
2013-11-09 00:19:16.930 BLELister[7116:60b] central state 5
2013-11-09 00:19:16.932 BLELister[7116:60b] No stored array to load
2013-11-09 00:19:16.933 BLELister[7116:60b] in discoveryDidRefreshWithNotification:
Test Suite 'Multiple Selected Tests' started at 2013-11-09 08:19:17 +0000
Test Suite 'BLEListerTests.xctest' started at 2013-11-09 08:19:17 +0000
Test Suite 'BSJSONParserTests' started at 2013-11-09 08:19:17 +0000
Test Suite 'BSJSONParserTests' finished at 2013-11-09 08:19:17 +0000.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'BSLeDiscoveryTests' started at 2013-11-09 08:19:17 +0000
Test Case '-[BSLeDiscoveryTests testFoundPeripherals]' started.
2013-11-09 00:19:17.023 BLELister[7116:60b] This block should run only one time. &once: 0x12a628, once: 668159976
2013-11-09 00:19:17.027 BLELister[7116:60b] [[BSLeDiscovery sharedInstance] <BSLeDiscovery: 0x14d3dc20>
2013-11-09 00:19:17.029 BLELister[7116:60b] [[BSLeDiscovery sharedInstance] centralManager] <CBCentralManager: 0x14e5c860>
2013-11-09 00:19:17.034 BLELister[7116:60b] CoreBluetooth[WARNING] <CBCentralManager: 0x14e5c860> is not powered on
2013-11-09 00:19:17.036 BLELister[7116:60b] In testBlock. foundPeripherals: (
)
2013-11-09 00:19:17.038 BLELister[7116:60b] central state 5
2013-11-09 00:19:17.038 BLELister[7116:60b] No stored array to load
2013-11-09 00:19:17.041 BLELister[7116:60b] in discoveryDidRefreshWithNotification:
2013-11-09 00:19:17.253 BLELister[7116:60b] in discoveryDidRefreshWithNotification:
2013-11-09 00:19:17.256 BLELister[7116:60b] notification.userInfo {
    RSSI = "-73";
    advertisementData =     {
        kCBAdvDataChannel = 39;
        kCBAdvDataIsConnectable = 1;
        kCBAdvDataLocalName = "BLE Shield";
        kCBAdvDataServiceUUIDs =         (
            "Unknown (<713d0000 503e4c75 ba943148 f18d941e>)"
        );
    };
    peripheral = "<CBPeripheral: 0x14e5bf70 identifier = DDAB0207-5E10-2902-5B03-CA3F0F466B40, Name = \"BLE Shield\", state = disconnected>";
}
/Users/stevebaker/Documents/projects/iOSProjects/BluetoothProjects/BLELister/Pods/SHTestCaseAdditions/SHTestCaseAdditions/OCUnit+SHTestCaseAdditions.m:64: error: -[BSLeDiscoveryTests testFoundPeripherals] : ((currentTime <= timeoutSeconds) is true) failed - Timed out
Test Case '-[BSLeDiscoveryTests testFoundPeripherals]' failed (30.039 seconds).
Test Suite 'BSLeDiscoveryTests' finished at 2013-11-09 08:19:47 +0000.
Executed 1 test, with 1 failure (0 unexpected) in 30.039 (30.039) seconds
Test Suite 'BSMasterViewControllerTests' started at 2013-11-09 08:19:47 +0000
Test Suite 'BSMasterViewControllerTests' finished at 2013-11-09 08:19:47 +0000.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'CBCentralManagerTests' started at 2013-11-09 08:19:47 +0000
Test Suite 'CBCentralManagerTests' finished at 2013-11-09 08:19:47 +0000.
Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'BLEListerTests.xctest' finished at 2013-11-09 08:19:47 +0000.
Executed 1 test, with 1 failure (0 unexpected) in 30.039 (30.041) seconds
Test Suite 'Multiple Selected Tests' finished at 2013-11-09 08:19:47 +0000.
Executed 1 test, with 1 failure (0 unexpected) in 30.039 (30.044) seconds